### ISSUE TITLE
Redundant use of cat

### ISSUE THREAD

**Issue by peti** [takenobu-hs/commandline-haskell#1]
Why do you use

    cat data.txt | ghc -e expr

instead of

    ghc <data.txt -e expr

...? The use of the pipe makes this  code less portable and complicates the semantics of exit code handling for no apparent gain?

**Comment by takenobu-hs** [comment]
Hi peti,

In actual use, it is better to use a redirect as you say.
In order to simplify the part of `ghc -e ...`, I represent the input part with pipeline in this article.
Thank you for your advice.
